export const CACHE_CONTROL = {
  recentComments: "public, max-age=30, stale-while-revalidate=120",
  mangaComments: "public, max-age=30, stale-while-revalidate=120",
  chapterComments: "public, max-age=30, stale-while-revalidate=120",
  genres: "public, max-age=300, stale-while-revalidate=600",
  mangaList: "public, max-age=30, stale-while-revalidate=120",
  mangaTop: "public, max-age=30, stale-while-revalidate=120",
  mangaRandom: "no-store",
  mangaDetail: "public, max-age=60, stale-while-revalidate=300",
  mangaChapters: "public, max-age=30, stale-while-revalidate=120",
  teamList: "public, max-age=30, stale-while-revalidate=120",
  teamDetail: "public, max-age=60, stale-while-revalidate=300",
  teamMangaList: "public, max-age=30, stale-while-revalidate=120",
  teamMembers: "public, max-age=60, stale-while-revalidate=300",
  teamUpdates: "public, max-age=30, stale-while-revalidate=120",
  userDetail: "public, max-age=60, stale-while-revalidate=300",
  userComments: "public, max-age=30, stale-while-revalidate=120",
  search: "no-store",
} as const;
